### ISSUE TITLE
请问这个可以使用lua编辑吗？

### ISSUE THREAD

**Issue by gaojiefeng** [CaptainCN/QCEditor#1]
请问这个可以使用lua编辑吗？，我lua比较熟，cpp相对差点，一直想写一个编辑器，看你写的这个编辑器和我想象的编辑器类似，这个可以导出到Lua层使用和修改吗？

**Comment by qcdong2016** [comment]
现在还没写完哈。解析和存储这部分还没写。做完肯定可以导出到lua。我平时也是用lua开发的。你有兴趣可以来一起啊。
